### ISSUE TITLE
[BUG] API Endpoint Guard: ReferenceError: request is not defined

### ISSUE THREAD

**Issue by sysmat** [mehdikhody/svelte-guard#3]
**Describe the bug**
[API Endpoint Guard](https://github.com/mehdikhody/svelte-guard?tab=readme-ov-file#api-endpoint-guard) doc request is not defined 

**To Reproduce**

1. just using documentation

**Expected behavior**
to have exact doc 

**Screenshots**

**Additional context**

```
"@sveltejs/adapter-auto": "^3.3.1",
"@sveltejs/kit": "^2.7.3",
"@sveltejs/vite-plugin-svelte": "^4.0.0",
"svelte": "^5.1.4",
"typescript": "^5.6.3",
"vite": "^5.4.10",

```

**Comment by mehdikhody** [comment]
The `request` object is a property of the `event` object. This was a typo in the documentation, and we will fix it very soon.

```typescript
// src/routes/api/-guard.ts
import type { Guard } from 'svelte-guard';

export const guard: Guard = async ({ request }) => {
	const header = request.headers.get('Authorization');
	const token = 'xxxxxxxxxxxxxxxx';
	if (!header || header !== `Bearer ${token}`) {
		return false;
	}

	return true;
};

// No reroute specified = 403 Forbidden on failure
```
